package com.prosup.proinsight.service;

import com.prosup.proinsight.adapter.out.persistence.AcademiaDocument;
import com.prosup.proinsight.adapter.out.persistence.MongoAcademiaDataRepository;
import com.prosup.proinsight.domain.model.Academia;
import com.prosup.proinsight.domain.model.Endereco;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.Optional;

@Service
public class AcademiaService {

    private final MongoAcademiaDataRepository repo;

    public AcademiaService(MongoAcademiaDataRepository repo) {
        this.repo = repo;
    }

    public Academia createProfile(String userId, Academia academia) {
        AcademiaDocument doc = toDocument(academia);
        doc.setUserId(userId);
        doc.setCreatedAt(Instant.now());
        doc.setUpdatedAt(Instant.now());
        AcademiaDocument saved = repo.save(doc);
        return toDomain(saved);
    }

    public Optional<Academia> findByUserId(String userId) {
        return repo.findAll().stream().filter(a -> userId.equals(a.getUserId())).findFirst().map(this::toDomain);
    }

    private Academia toDomain(AcademiaDocument d) {
        if (d == null) return null;
        Endereco.Endereco e = null;
        if (d.getEndereco() != null) {
            var ed = d.getEndereco();
            e = new Endereco.Endereco(ed.getRua(), ed.getNumero(), ed.getCidade(), ed.getEstado(), ed.getCep());
        }
        return new Academia(d.getId(), d.getUserId(), d.getNomeFantasia(), d.getRazaoSocial(), d.getCnpj(), e, d.getTelefone(), d.getCreatedAt(), d.getUpdatedAt());
    }

    private AcademiaDocument toDocument(Academia a) {
        if (a == null) return null;
        AcademiaDocument d = new AcademiaDocument();
        // Note: setting the id from domain object will override any id generated by MongoDB.
        // If the domain `Academia` has null id, MongoDB will generate one on save.
        // Keep this behavior as-is; do not modify unless you intend to provide an explicit id.
        d.setId(a.getId());
        d.setNomeFantasia(a.getNomeFantasia());
        d.setRazaoSocial(a.getRazaoSocial());
        d.setCnpj(a.getCnpj());
        if (a.getEndereco() != null) {
            AcademiaDocument.Endereco ed = new AcademiaDocument.Endereco();
            ed.setRua(a.getEndereco().getRua());
            ed.setNumero(a.getEndereco().getNumero());
            ed.setCidade(a.getEndereco().getCidade());
            ed.setEstado(a.getEndereco().getEstado());
            ed.setCep(a.getEndereco().getCep());
            d.setEndereco(ed);
        }
        d.setTelefone(a.getTelefone());
        return d;
    }
}

