package com.prosup.proinsight.domain.enums;

public enum Permissao {
    CLIENTES_CRIAR,
    CLIENTES_LER,
    CLIENTES_ATUALIZAR,
    CLIENTES_EXCLUIR,

    AVALIACOES_CRIAR,
    AVALIACOES_LER,
    AVALIACOES_ATUALIZAR,
    AVALIACOES_EXCLUIR,

    AVALIADORES_CRIAR,
    AVALIADORES_LER,
    AVALIADORES_ATUALIZAR,

    PROTOCOLOS_LER,

    USUARIOS_CRIAR,
    USUARIOS_LER,
    USUARIOS_ATUALIZAR,
    USUARIOS_EXCLUIR,

    ACADEMIAS_CRIAR,
    ACADEMIAS_LER,
    ACADEMIAS_ATUALIZAR,

    RELATORIOS_LER,
    RELATORIOS_EXPORTAR,

    SUPER_ADMIN
}
